<?php namespace App\Controllers;
/**
* THIS CONTROLER CODEIGNITER 4
* Codeigniter Version 4.x
* Generated by LigatCode
**/
use App\Models\JurusanModel;

class Jurusan extends BaseController
{
    /**
	 * Class constructor.
     */	
    protected $PageData;
	protected $Model; //Default Models Of this Controler
	public function __construct()
	{
		$this->Model = new 'JurusanModel'(); //Set Default Models Of this Controler
		$this->PageData = $this->attributePage(); //Attribute Of Page
    }
    
    //ATRIBUTE THIS PAGE
    private function attributePage()
	{
		return  [
			'title' => 'LigatCode | Jurusan',
			'app' => 'LigatCode',
		];
    }

    //INDEX 
    public function index()
	{
		$data = [
			'AttributePage' =>$this->PageData,
			'content' => 'Create Pages',
			'data' => $this->Model->findAll(),
		];
		return view('jurusan/index_jurusan', $data);
    }

    //READ
    public function read($id)
	{
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Read Pages',
			'data' => $this->Model->find($id) //find on data
		];
		return view('jurusan/read_jurusan', $data);
    }

    //CREATE
    public function create()
	{
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Create Pages',
			'action' => site_url('Jurusan/create_action'),
			'data' =>   [
					    ]
		];
		return view('jurusan/form_jurusan', $data);
    }
    
    //ACTION CREATE
	public function create_action()
	{
		$data =[
			'jurusan' => $this->request->getVar('Jurusan'),
        ];
		$this->Model->save($data);
		session()->setFlashdata('message', 'Create Record Success');
		return redirect()->to(base_url('/Jurusan'));
    }
    
    //UPDATE
	public function update($id)
	{
		$dataFind = $this->Model->find($id);
		if($dataFind == false){
			return redirect()->to(base_url('/Jurusan'));
		}
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Edite Pages',
			'action' => 'Jurusan/update_action',
			'data' => $this->Model->find($id),
        ];
		session()->setFlashdata('message', 'Update Record Success');
		return view('jurusan/form_jurusan', $data);
    }
    
    //ACTION UPDATE
    public function update_action()
	{
		return view('jurusan');
	}

    //DELETE
	public function delete($id)
	{
		$row = $this->Model->find(['id_jurusan' => $id]);
		if ($row) {
            $this->Model->delete($id);
            session()->setFlashdata('message', 'Delete Record Success');
            return redirect()->to(base_url('/jurusan'));
        } else {
            session()->setFlashdata('message', 'Record Not Found');
            return redirect()->to(base_url('/jurusan'));
        }

    }

    //RULES
    public function _rules() 
    {

	$this->form_validation->set_rules('id_jurusan', 'id_jurusan', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }


///////////////////////////////////////////////////
///////////////////////////////////////////////////
///////////////////////////////////////////////////

    function __construct()
    {
        parent::__construct();
        $this->load->model('JurusanModel');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'jurusan/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'jurusan/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'jurusan/index.html';
            $config['first_url'] = base_url() . 'jurusan/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->JurusanModel->total_rows($q);
        $jurusan = $this->JurusanModel->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'jurusan_data' => $jurusan,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('jurusan/index_jurusan', $data);
    }

    public function read($id) 
    {
        $row = $this->JurusanModel->get_by_id($id);
        if ($row) {
            $data = array(
	    );
            $this->load->view('jurusan/read_jurusan', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jurusan'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('jurusan/create_action'),
	);
        $this->load->view('jurusan/form_jurusan', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
	    );

            $this->JurusanModel->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('jurusan'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->JurusanModel->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('jurusan/update_action'),
	    );
            $this->load->view('jurusan/form_jurusan', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jurusan'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_jurusan', TRUE));
        } else {
            $data = array(
	    );

            $this->JurusanModel->update($this->input->post('id_jurusan', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('jurusan'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->JurusanModel->get_by_id($id);

        if ($row) {
            $this->JurusanModel->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('jurusan'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jurusan'));
        }
    }

    public function _rules() 
    {

	$this->form_validation->set_rules('id_jurusan', 'id_jurusan', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Jurusan.php */
/* Location: ./app/controllers/Jurusan.php */
/* Please DO NOT modify this information : */
/* Generated by Ligatcode Codeigniter 4 CRUD Generator 2020-08-30 12:39:15 */