<?php
$string ="<?php namespace App\\Controllers;
/**
* THIS CONTROLER CODEIGNITER 4
* Codeigniter Version 4.x
* Generated by LigatCode
**/
use App\\Models\\$m;

class " . $c . " extends BaseController
{
    /**
	 * Class constructor.
     */	
    protected \$PageData;
    protected \$Model; //Default Models Of this Controler
    protected \$pager;
	public function __construct()
	{
		\$this->Model = new $m(); //Set Default Models Of this Controler
        \$this->PageData = \$this->attributePage(); //Attribute Of Page
        \$pager = \Config\Services::pager();
    }
    
    //ATRIBUTE THIS PAGE
    private function attributePage()
	{
		return  [
			'title' => 'LigatCode | $c',
			'app' => 'LigatCode',
		];
    }

    //INDEX 
    public function index()
	{
		\$data = [
			'AttributePage' =>\$this->PageData,
			'content' => 'Create Pages',
            'data' => \$this->Model->paginate(5, 'paging'),
            'pager' => \$this->Model->pager
		];
		return view('$c_url/$v_list', \$data);
    }

    //READ
    public function read(\$id)
	{
		\$data = [
			'AttributePage' => \$this->PageData,
			'content' => 'Read Pages',
			'data' => \$this->Model->find(\$id) //find on data
		];
		return view('$c_url/$v_read', \$data);
    }

    //CREATE
    public function create()
	{
		\$data = [
			'AttributePage' => \$this->PageData,
			'content' => 'Create Pages',
			'action' => site_url('$c/create_action'),
			'data' =>   [";
                        //'$c' => set_value('$c'),

                        foreach ($all as $row) {
                            if(isset($_POST['field_'.$row['column_name']]) && isset($_POST['generate']))  //meedun code selected filed
                            { 
                                $string .= "\n\t\t\t\t\t     '" . $row['column_name'] . "' => set_value('" . $row['column_name'] . "'),";
                            }
                            if(isset($_POST['generateall']))  //meedun code
                            {
                                $string .= "\n\t\t\t\t\t     '" . $row['column_name'] . "' => set_value('" . $row['column_name'] . "'),";
                            }
                        }
$string .="
					    ]
		];
		return view('$c_url/$v_form', \$data);
    }
    
    //ACTION CREATE
	public function create_action()
	{
		\$data =[";
			  foreach ($all as $row) {
                            if(isset($_POST['field_'.$row['column_name']]) && isset($_POST['generate']))  //meedun code selected filed
                            { 
                                $string .= "\n\t\t\t\t     '" . $row['column_name'] . "' => \$this->request->getVar('" . $row['column_name'] . "'),";
                            }
                            if(isset($_POST['generateall']))  //meedun code
                            {
                                $string .= "\n\t\t\t\t     '" . $row['column_name'] . "' => \$this->request->getVar('" . $row['column_name'] . "'),";
                            }
                        }
$string.="
        \n\t\t\t\t];
		\$this->Model->save(\$data);
		session()->setFlashdata('message', 'Create Record Success');
		return redirect()->to(base_url('/$c'));
    }
    
    //UPDATE
	public function update(\$id)
	{
		\$dataFind = \$this->Model->find(\$id);
		if(\$dataFind == false){
			return redirect()->to(base_url('/$c'));
		}
		\$data = [
			'AttributePage' => \$this->PageData,
			'content' => 'Edite Pages',
			'action' => '$c_url/update_action',
			'data' => \$this->Model->find(\$id),
        ];
		session()->setFlashdata('message', 'Update Record Success');
		return view('$c_url/$v_form', \$data);
    }
    
    //ACTION UPDATE
   	public function update_action()
	{
		\$id = \$this->request->getVar('$pk');
		\$row = \$this->Model->find(['$pk' => \$id]);

			\$data =[";
                foreach ($all as $row) {
                            if(isset($_POST['field_'.$row['column_name']]) && isset($_POST['generate']))  //meedun code selected filed
                            { 
                                $string .= "\n\t\t\t\t    '" . $row['column_name'] . "' => \$this->request->getVar('" . $row['column_name'] . "'),";
                            }
                            if(isset($_POST['generateall']))  //meedun code
                            {
                                $string .= "\n\t\t\t\t     '" . $row['column_name'] . "' => \$this->request->getVar('" . $row['column_name'] . "'),";
                            }
                        }
$string .="
                    ];
            \$this->Model->save(\$data);
			session()->setFlashdata('message', 'Update Record Success');
			
			return redirect()->to(base_url('$c_url'));
		
	}

    //DELETE
	public function delete(\$id)
	{
		\$row = \$this->Model->find(['$pk' => \$id]);
		if (\$row) {
            \$this->Model->delete(\$id);
            session()->setFlashdata('message', 'Delete Record Success');
            return redirect()->to(base_url('/$c_url'));
        } else {
            session()->setFlashdata('message', 'Record Not Found');
            return redirect()->to(base_url('/$c_url'));
        }

    }

    //RULES
    public function _rules() 
    {";
foreach ($non_pk as $row) {
    if(isset($_POST['field_'.$row['column_name']]) && isset($_POST['generate']))  //meedun code selected filed
    { 
        $int = $row['data_type'] == 'int' || $row['data_type'] == 'double' || $row['data_type'] == 'decimal' ? '|numeric' : '';
        $string .= "\n\t\$this->form_validation->set_rules('".$row['column_name']."', '".  strtolower(label($row['column_name']))."', 'trim|required$int');";
    } 
    if(isset($_POST['generateall']))  //meedun code
    {
        $int = $row['data_type'] == 'int' || $row['data_type'] == 'double' || $row['data_type'] == 'decimal' ? '|numeric' : '';
        $string .= "\n\t\$this->form_validation->set_rules('".$row['column_name']."', '".  strtolower(label($row['column_name']))."', 'trim|required$int');";
    }
}    
$string .= "\n\n\t\$this->form_validation->set_rules('$pk', '$pk', 'trim');";
$string .= "\n\t\$this->form_validation->set_error_delimiters('<span class=\"text-danger\">', '</span>');
    }";


///////////////////////////////////////////////////
///////////////////////////////////////////////////
///////////////////////////////////////////////////

//     function __construct()
//     {
//         parent::__construct();
//         \$this->load->model('$m');
//         \$this->load->library('form_validation');";

// if ($jenis_tabel <> 'reguler_table') {
//     $string .= "  \n\t\$this->load->library('datatables');";
// }
        
// $string .= "
//     }";

// if ($jenis_tabel == 'reguler_table') {
    
// $string .= "\n\n    public function index()
//     {
//         \$q = urldecode(\$this->input->get('q', TRUE));
//         \$start = intval(\$this->input->get('start'));
        
//         if (\$q <> '') {
//             \$config['base_url'] = base_url() . '$c_url/index.html?q=' . urlencode(\$q);
//             \$config['first_url'] = base_url() . '$c_url/index.html?q=' . urlencode(\$q);
//         } else {
//             \$config['base_url'] = base_url() . '$c_url/index.html';
//             \$config['first_url'] = base_url() . '$c_url/index.html';
//         }

//         \$config['per_page'] = 10;
//         \$config['page_query_string'] = TRUE;
//         \$config['total_rows'] = \$this->" . $m . "->total_rows(\$q);
//         \$$c_url = \$this->" . $m . "->get_limit_data(\$config['per_page'], \$start, \$q);

//         \$this->load->library('pagination');
//         \$this->pagination->initialize(\$config);

//         \$data = array(
//             '" . $c_url . "_data' => \$$c_url,
//             'q' => \$q,
//             'pagination' => \$this->pagination->create_links(),
//             'total_rows' => \$config['total_rows'],
//             'start' => \$start,
//         );
//         \$this->load->view('$c_url/$v_list', \$data);
//     }";

// } else {
    
// $string .="\n\n    public function index()
//     {
//         \$this->load->view('$c_url/$v_list');
//     } 
    
//     public function json() {
//         header('Content-Type: application/json');
//         echo \$this->" . $m . "->json();
//     }";

// }
    
// $string .= "\n\n    public function read(\$id) 
//     {
//         \$row = \$this->" . $m . "->get_by_id(\$id);
//         if (\$row) {
//             \$data = array(";
// foreach ($all as $row) {
//     if(isset($_POST['field_'.$row['column_name']]) && isset($_POST['generate']))  //meedun code selected filed
//     { 
//         $string .= "\n\t\t'" . $row['column_name'] . "' => \$row->" . $row['column_name'] . ",";
//     }
//     if(isset($_POST['generateall']))  //meedun code
//     {
//         $string .= "\n\t\t'" . $row['column_name'] . "' => \$row->" . $row['column_name'] . ",";
//     }
// }
// $string .= "\n\t    );
//             \$this->load->view('$c_url/$v_read', \$data);
//         } else {
//             \$this->session->set_flashdata('message', 'Record Not Found');
//             redirect(site_url('$c_url'));
//         }
//     }

//     public function create() 
//     {
//         \$data = array(
//             'button' => 'Create',
//             'action' => site_url('$c_url/create_action'),";
// foreach ($all as $row) {
//     if(isset($_POST['field_'.$row['column_name']]) && isset($_POST['generate']))  //meedun code selected filed
//     { 
//         $string .= "\n\t    '" . $row['column_name'] . "' => set_value('" . $row['column_name'] . "'),";
//     }
//     if(isset($_POST['generateall']))  //meedun code
//     {
//         $string .= "\n\t    '" . $row['column_name'] . "' => set_value('" . $row['column_name'] . "'),";
//     }
// }
// $string .= "\n\t);
//         \$this->load->view('$c_url/$v_form', \$data);
//     }
    
//     public function create_action() 
//     {
//         \$this->_rules();

//         if (\$this->form_validation->run() == FALSE) {
//             \$this->create();
//         } else {
//             \$data = array(";
// foreach ($non_pk as $row) {
//     if(isset($_POST['field_'.$row['column_name']]) && isset($_POST['generate']))  //meedun code selected filed
//     { 
//         $string .= "\n\t\t'" . $row['column_name'] . "' => \$this->input->post('" . $row['column_name'] . "',TRUE),";
//     }
//     if(isset($_POST['generateall']))  //meedun code
//     {
//         $string .= "\n\t\t'" . $row['column_name'] . "' => \$this->input->post('" . $row['column_name'] . "',TRUE),";
//     }
// }
// $string .= "\n\t    );

//             \$this->".$m."->insert(\$data);
//             \$this->session->set_flashdata('message', 'Create Record Success');
//             redirect(site_url('$c_url'));
//         }
//     }
    
//     public function update(\$id) 
//     {
//         \$row = \$this->".$m."->get_by_id(\$id);

//         if (\$row) {
//             \$data = array(
//                 'button' => 'Update',
//                 'action' => site_url('$c_url/update_action'),";
// foreach ($all as $row) {
//     if(isset($_POST['field_'.$row['column_name']]) && isset($_POST['generate']))  //meedun code selected filed
//     { 
//         $string .= "\n\t\t'" . $row['column_name'] . "' => set_value('" . $row['column_name'] . "', \$row->". $row['column_name']."),";
//     }
//     if(isset($_POST['generateall']))  //meedun code
//     {
//         $string .= "\n\t\t'" . $row['column_name'] . "' => set_value('" . $row['column_name'] . "', \$row->". $row['column_name']."),";
//     }
// }
// $string .= "\n\t    );
//             \$this->load->view('$c_url/$v_form', \$data);
//         } else {
//             \$this->session->set_flashdata('message', 'Record Not Found');
//             redirect(site_url('$c_url'));
//         }
//     }
    
//     public function update_action() 
//     {
//         \$this->_rules();

//         if (\$this->form_validation->run() == FALSE) {
//             \$this->update(\$this->input->post('$pk', TRUE));
//         } else {
//             \$data = array(";
// foreach ($non_pk as $row) {
//     if(isset($_POST['field_'.$row['column_name']]) && isset($_POST['generate']))  //meedun code selected filed
//     {  
//         $string .= "\n\t\t'" . $row['column_name'] . "' => \$this->input->post('" . $row['column_name'] . "',TRUE),";
//     }
//     if(isset($_POST['generateall']))  //meedun code
//     {
//         $string .= "\n\t\t'" . $row['column_name'] . "' => \$this->input->post('" . $row['column_name'] . "',TRUE),";
//     }
// }    
// $string .= "\n\t    );

//             \$this->".$m."->update(\$this->input->post('$pk', TRUE), \$data);
//             \$this->session->set_flashdata('message', 'Update Record Success');
//             redirect(site_url('$c_url'));
//         }
//     }
    
//     public function delete(\$id) 
//     {
//         \$row = \$this->".$m."->get_by_id(\$id);

//         if (\$row) {
//             \$this->".$m."->delete(\$id);
//             \$this->session->set_flashdata('message', 'Delete Record Success');
//             redirect(site_url('$c_url'));
//         } else {
//             \$this->session->set_flashdata('message', 'Record Not Found');
//             redirect(site_url('$c_url'));
//         }
//     }

//     public function _rules() 
//     {";
// foreach ($non_pk as $row) {
//     if(isset($_POST['field_'.$row['column_name']]) && isset($_POST['generate']))  //meedun code selected filed
//     { 
//         $int = $row['data_type'] == 'int' || $row['data_type'] == 'double' || $row['data_type'] == 'decimal' ? '|numeric' : '';
//         $string .= "\n\t\$this->form_validation->set_rules('".$row['column_name']."', '".  strtolower(label($row['column_name']))."', 'trim|required$int');";
//     } 
//     if(isset($_POST['generateall']))  //meedun code
//     {
//         $int = $row['data_type'] == 'int' || $row['data_type'] == 'double' || $row['data_type'] == 'decimal' ? '|numeric' : '';
//         $string .= "\n\t\$this->form_validation->set_rules('".$row['column_name']."', '".  strtolower(label($row['column_name']))."', 'trim|required$int');";
//     }
// }    
// $string .= "\n\n\t\$this->form_validation->set_rules('$pk', '$pk', 'trim');";
// $string .= "\n\t\$this->form_validation->set_error_delimiters('<span class=\"text-danger\">', '</span>');
//     }";

// if ($export_excel == '1') {
//     $string .= "\n\n    public function excel()
//     {
//         \$this->load->helper('exportexcel');
//         \$namaFile = \"$table_name.xls\";
//         \$judul = \"$table_name\";
//         \$tablehead = 0;
//         \$tablebody = 1;
//         \$nourut = 1;
//         //penulisan header
//         header(\"Pragma: public\");
//         header(\"Expires: 0\");
//         header(\"Cache-Control: must-revalidate, post-check=0,pre-check=0\");
//         header(\"Content-Type: application/force-download\");
//         header(\"Content-Type: application/octet-stream\");
//         header(\"Content-Type: application/download\");
//         header(\"Content-Disposition: attachment;filename=\" . \$namaFile . \"\");
//         header(\"Content-Transfer-Encoding: binary \");

//         xlsBOF();

//         \$kolomhead = 0;
//         xlsWriteLabel(\$tablehead, \$kolomhead++, \"No\");";
// foreach ($non_pk as $row) {
//     if(isset($_POST['field_'.$row['column_name']]) && isset($_POST['generate']))  //meedun code selected filed
//     { 
//         $column_name = label($row['column_name']);
//         $string .= "\n\txlsWriteLabel(\$tablehead, \$kolomhead++, \"$column_name\");";
//     }
//     if(isset($_POST['generateall']))  //meedun code
//     {
//         $column_name = label($row['column_name']);
//         $string .= "\n\txlsWriteLabel(\$tablehead, \$kolomhead++, \"$column_name\");";
//     }
// }
// $string .= "\n\n\tforeach (\$this->" . $m . "->get_all() as \$data) {
//             \$kolombody = 0;

//             //ubah xlsWriteLabel menjadi xlsWriteNumber untuk kolom numeric
//             xlsWriteNumber(\$tablebody, \$kolombody++, \$nourut);";
// foreach ($non_pk as $row) {
//     if(isset($_POST['field_'.$row['column_name']]) && isset($_POST['generate']))  //meedun code selected filed
//     { 
//         $column_name = $row['column_name'];
//         $xlsWrite = $row['data_type'] == 'int' || $row['data_type'] == 'double' || $row['data_type'] == 'decimal' ? 'xlsWriteNumber' : 'xlsWriteLabel';
//         $string .= "\n\t    " . $xlsWrite . "(\$tablebody, \$kolombody++, \$data->$column_name);";
//     }
//     if(isset($_POST['generateall']))  //meedun code
//     {
//         $column_name = $row['column_name'];
//         $xlsWrite = $row['data_type'] == 'int' || $row['data_type'] == 'double' || $row['data_type'] == 'decimal' ? 'xlsWriteNumber' : 'xlsWriteLabel';
//         $string .= "\n\t    " . $xlsWrite . "(\$tablebody, \$kolombody++, \$data->$column_name);";
//     }
// }
// $string .= "\n\n\t    \$tablebody++;
//             \$nourut++;
//         }

//         xlsEOF();
//         exit();
//     }";
// }

// if ($export_word == '1') {
//     $string .= "\n\n    public function word()
//     {
//         header(\"Content-type: application/vnd.ms-word\");
//         header(\"Content-Disposition: attachment;Filename=$table_name.doc\");

//         \$data = array(
//             '" . $table_name . "_data' => \$this->" . $m . "->get_all(),
//             'start' => 0
//         );
        
//         \$this->load->view('" . $c_url ."/". $v_doc . "',\$data);
//     }";
// }

// if ($export_pdf == '1') {
//     $string .= "\n\n    function pdf()
//     {
//         \$data = array(
//             '" . $table_name . "_data' => \$this->" . $m . "->get_all(),
//             'start' => 0
//         );
        
//         ini_set('memory_limit', '32M');
//         \$html = \$this->load->view('" . $c_url ."/". $v_pdf . "', \$data, true);
//         \$this->load->library('pdf');
//         \$pdf = \$this->pdf->load();
//         \$pdf->WriteHTML(\$html);
//         \$pdf->Output('" . $table_name . ".pdf', 'D'); 
//     }";
// }

 $string .= "\n\n}\n\n/* End of file $c_file */
 /* Location: ./app/controllers/$c_file */
 /* Please DO NOT modify this information : */
 /* Generated by Ligatcode Codeigniter 4 CRUD Generator ".date('Y-m-d H:i:s')." */";

$result_controller = createFile($string, $target . "controllers/" . $c_file);

?>